static const char merge_glsl_shader_raw[] = 
"#ifdef FRAGMENT_SHADER\n"
"\n"
"in vec4 PSin_p;\n"
"in vec2 PSin_t;\n"
"in vec4 PSin_c;\n"
"\n"
"uniform vec4 BGColor;\n"
"\n"
"layout(binding = 0) uniform sampler2D TextureSampler;\n"
"\n"
"layout(location = 0) out vec4 SV_Target0;\n"
"\n"
"void ps_main0()\n"
"{\n"
"    vec4 c = texture(TextureSampler, PSin_t);\n"
"    // Note: clamping will be done by fixed unit\n"
"    c.a *= 2.0f;\n"
"    SV_Target0 = c;\n"
"}\n"
"\n"
"void ps_main1()\n"
"{\n"
"    vec4 c = texture(TextureSampler, PSin_t);\n"
"    c.a = BGColor.a;\n"
"    SV_Target0 = c;\n"
"}\n"
"\n"
"#endif\n"
;
