static const char merge_glsl_shader_raw[] = 
"#ifdef VERTEX_SHADER\n"
"layout(location = 0) in vec4 a_pos;\n"
"layout(location = 1) in vec2 a_tex;\n"
"layout(location = 0) out vec2 v_tex;\n"
"void main()\n"
"{\n"
	"gl_Position = vec4(a_pos.x, -a_pos.y, a_pos.z, a_pos.w);\n"
	"v_tex = a_tex;\n"
"}\n"
"#endif\n"
"#ifdef FRAGMENT_SHADER\n"
"layout(location = 0) in vec2 v_tex;\n"
"layout(location = 0) out vec4 o_col0;\n"
"layout(push_constant) uniform cb10\n"
"{\n"
		"vec4 BGColor;\n"
"};\n"
"layout(set = 0, binding = 0) uniform sampler2D samp0;\n"
"void ps_main0()\n"
"{\n"
		"vec4 c = texture(samp0, v_tex);\n"
		"// Note: clamping will be done by fixed unit\n"
		"c.a *= 2.0f;\n"
		"o_col0 = c;\n"
"}\n"
"void ps_main1()\n"
"{\n"
		"vec4 c = texture(samp0, v_tex);\n"
		"c.a = BGColor.a;\n"
		"o_col0 = c;\n"
"}\n"
"#endif\n"
;
