name: CI (Linux armhf)
on: [push, pull_request]
jobs:
  build-linux-armhf:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        whoami
        sudo bash -c 'echo ''deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports focal main restricted universe'' > /etc/apt/sources.list.d/armhf.list'
        sudo sed -i 's/^deb \([^[]\)/deb [arch=amd64] \1/' /etc/apt/sources.list
        sudo dpkg --add-architecture armhf
        sudo apt-get update -qq
        sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        .github/extract-foreign-all.sh armhf
    - name: configure
      run: DUMP_CONFIG_LOG=1 CROSS_COMPILE=arm-linux-gnueabihf- SDL_CONFIG=usr/bin/sdl-config PATH=$PATH:usr/bin CFLAGS='-Iusr/include/ -Iusr/include/SDL' LDFLAGS='-Lusr/lib/arm-linux-gnueabihf/ -Llib/arm-linux-gnueabihf/ -Wl,-rpath-link=lib/arm-linux-gnueabihf/,-rpath-link=usr/lib/arm-linux-gnueabihf/,-rpath-link=usr/lib/arm-linux-gnueabihf/pulseaudio/' ./configure
    - name: make
      run: make -j$(getconf _NPROCESSORS_ONLN)
