name: CI (libretro)
on: [push, pull_request]
jobs:
  build-libretro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: make
      run: make -j$(getconf _NPROCESSORS_ONLN) -f Makefile.libretro

  build-libretro-win32:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y gcc-mingw-w64
    - name: make
      run: make -j$(getconf _NPROCESSORS_ONLN) -f Makefile.libretro platform=win32 CC=x86_64-w64-mingw32-gcc

  build-libretro-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: ndk-build
      run: ${ANDROID_NDK_HOME}/ndk-build -j$(getconf _NPROCESSORS_ONLN) --no-print-directory -C jni/
