name: Test python

on:
  push:
    branches:
      - add-ci-testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install git cmake capnproto zlib1g-dev g++ build-essential python3-dev python3-pip pkg-config libzip-dev software-properties-common libbz2-dev xvfb python3-opengl

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip cmake wheel setuptools pytest

      - name: Run python tests
        run: |
          pip install -e .
          xvfb-run -s '-screen 0 1024x768x24' pytest
